COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
  SECRETS_MANAGER:
    NAME: "my-database-secret"
    REGION: "eu-north-1"

production:
  <<: *common
  SECRETS_MANAGER:
    NAME: "my-database-secret"
    REGION: "eu-north-1"

ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: "ubuntu"  # якщо create_app потребує
  MYSQL_ROOT_PASSWORD: null   # залишаємо пустим
