name: Deploy to EC2

on:
  push:
    branches:
      - main  # або твоя гілка, яку ти хочеш деплоїти автоматично

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клон репозиторію
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Встановити SSH ключ з GitHub Secrets
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # 3. Підключитись до EC2 та виконати deploy.sh
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'bash -s' < ./deploy.sh
